// export const REAL_WIDTH = 55;  //地图实际大小
// export const REAL_HEIGH = 44;
// export const MAP_W = 700; //网页地图大小
export const REAL_WIDTH = 4;  //地图实际大小
export const REAL_HEIGH = 5.8;
export const MAP_W = 500; //网页地图大小
export const MAP_H = MAP_W/REAL_WIDTH*REAL_HEIGH;
export const RATIO = MAP_W/REAL_WIDTH; //真实地图与网页地图比值
export const ANCHOR_W = 30; //绘图anchor宽度
export const ANCHOR_H = 30; //绘图anchor高度
export const TAG_W = 30; //绘图tag宽度
export const TAG_H = 30; //绘图tag高度
export const TRIGGER_RADIS = 15; //触发事件的半径